module.exports = function(app) {
	var Mongoose = require('Mongoose');
	var casoSchema = new Mongoose.Schema({
		nome: {type: String, required: true},
		sexo: Number,
		telefone: {type: String},
		email: {type: String},
		matricula: {type: String, required: true},
		curso: {type: String, required: true},
		periodo: {type: Number, required: true},
		data: {type: String, required: true},
		observacoes: {type: String},
		demandas: {
			desequilibrioPsicologico: Number,
			orientacaoSecular: Number,
			orientacaoPedagogica: Number,
			muitasFaltas: Number,
			problemaSocioEconomico: Number,
			atrasosConstantes: Number,
			bulling: Number,
			desmotivacaoRendimento: Number,
			desmotivacaoCurso: Number,
			dificuldadeAprendizagem: Number,
			problemaDisciplinarLeve: Number,
			problemaDisciplinarMedio: Number,
			problemaDisciplinarGrave: Number,
			problemaComportamento: Number,
			conflitoFamiliar: Number,
			conflitoRelacionalAfetivo: Number,
			conflitoOpcaoSexual: Number,
			problemaRelacionamentoMae: Number,
			problemaRelacionamentoPai:  Number,
			problemaRelacionamentoCasa: Number,
			problemaRelacionamentoAluno: Number,
			problemaRelacionamentoProfessor: Number,
			situacaoAbuso: Number,
			situacaoExclusao: Number,
			situacaoTimidez: Number,
			separacaoPais: Number
		},
		encaminhamentos: {
			psicologiaEscolar: Number,
			servicoSocial: Number,
			setorMedico: Number,
			chamarPais: Number,
			chamarProfessores: Number,
			acionarCoordenacao: Number,
			advertencia: Number,
			repreensao: Number,
			suspesaoEscolar: Number,
			cumprimentoMSE: Number,
			cancelarMatricula: Number,
			trancarDisciplina: Number,
			trancarPeriodoCompulsorio: Number,
			trancarPeriodoVoluntario: Number,
			visitaDomiciliar: Number,
			atendimentoDomiciliar: Number,
			rotinaEstudo: Number,
			centroAprendizagem: Number,
			mudarTurno: Number,
			conversar: Number
		},
		contexto: {type: String, required: true},
		atendidoPor: {type: String, required: true},
		classe: {type: String, required: true}
	});
	
	return Caso = Mongoose.model('Caso', casoSchema);
};